#!/usr/bin/env bash
set -e

ORIGIN=$(pwd)
BASE="scripts/packages"

source $(dirname $0)/version

mkdir -p "${ORIGIN}/dist"

for i in "${BASE}"/*; do
	echo "build-package: Building ${i}"

	cd "${ORIGIN}/${i}"

	if [ ! -f "Dockerfile" ]; then
		echo "WARN: Skipping"

		continue
	fi

	if [ -x "prebuild.sh" ]; then
		./prebuild.sh
	fi

	DISTRO=$(basename "${i}")
	IMAGE_NAME="hbm-build-${DISTRO}"

	docker build -t "${IMAGE_NAME}" -f Dockerfile .
	CONTAINER_ID=$(docker create "${IMAGE_NAME}" ${VERSION} ${RELEASE})
	docker start -a "${CONTAINER_ID}"

	code=$?


	if [ "${code}" == "0" ]; then
		docker cp "${CONTAINER_ID}:/tmp/dist/." "${ORIGIN}/dist/"
	fi

	docker rm "${CONTAINER_ID}"

	if [ -d "build" ]; then
		rm -rf build
	fi
done

echo "build-package: DONE"
